const flatHeaders = [
  { id: "term", name: "Term", parentId: null },
  { id: "homework", name: "Homework", parentId: "term" },
  { id: "homework1", name: "Homework 1", parentId: "homework" },
  { id: "homework1_marks", name: "Marks", parentId: "homework1" },
  { id: "homework1_comment", name: "Comment", parentId: "homework1" },
  { id: "homework_total", name: "Total", parentId: "homework" },
  { id: "homework_total_score", name: "Score", parentId: "homework_total" },
  {
    id: "homework_evaluationStatus",
    name: "Evaluation Status",
    parentId: "homework",
  },
  { id: "classwork", name: "Classwork", parentId: "term" },
  { id: "classwork1", name: "Classwork 1", parentId: "classwork" },
  { id: "classwork1_marks", name: "Marks", parentId: "classwork1" },
  { id: "classwork1_comment", name: "Comment", parentId: "classwork1" },
  { id: "classwork_total", name: "Total", parentId: "classwork" },
  { id: "classwork_total_score", name: "Score", parentId: "classwork_total" },
  {
    id: "classwork_evaluationStatus",
    name: "Evaluation Status",
    parentId: "classwork",
  },
  { id: "finalAssessment", name: "Final Assessment", parentId: "term" },
  {
    id: "finalAssessment1",
    name: "Final Assessment 1",
    parentId: "finalAssessment",
  },
  {
    id: "finalAssessment1_marks",
    name: "Marks",
    parentId: "finalAssessment1",
  },
  {
    id: "finalAssessment1_comment",
    name: "Comment",
    parentId: "finalAssessment1",
  },
  { id: "finalAssessment_total", name: "Total", parentId: "finalAssessment" },
  {
    id: "finalAssessment_total_score",
    name: "Score",
    parentId: "finalAssessment_total",
  },
  {
    id: "finalAssessment_evaluationStatus",
    name: "Evaluation Status",
    parentId: "finalAssessment",
  },
  { id: "total", name: "Total", parentId: "term" },
  { id: "total_score", name: "Score", parentId: "total" },
  { id: "total_grade", name: "Grade", parentId: "total" },
  {
    id: "total_evaluationStatus",
    name: "Evaluation Status",
    parentId: "total",
  },
];

const studentData = [
  {
    name: "Ari Nolan",
    homework1_marks: 50,
    homework1_comment: "Great job",
    homework_total_score: 90,
    homework_evaluationStatus: "Completed",
    classwork1_marks: 50,
    classwork1_comment: "Great job",
    classwork_total_score: 90,
    classwork_evaluationStatus: "Completed",
    finalAssessment1_marks: 50,
    finalAssessment1_comment: "Great job",
    finalAssessment_total_score: 90,
    finalAssessment_evaluationStatus: "Completed",
    total_score: 90,
    total_grade: "A",
    total_evaluationStatus: "Completed",
  },
  {
    name: "Brendan Rogers",
    homework1_marks: {
      marks: 50,
      error: false,
    },
    homework1_comment: "Great job",
    homework_total_score: 90,
    homework_evaluationStatus: "Completed",
    classwork1_marks: 50,
    classwork1_comment: "Great job",
    classwork_total_score: 90,
    classwork_evaluationStatus: "Completed",
    finalAssessment1_marks: 50,
    finalAssessment1_comment: "Great job",
    finalAssessment_total_score: 90,
    finalAssessment_evaluationStatus: "Completed",
    total_score: 90,
    total_grade: "A",
    total_evaluationStatus: "Completed",
  },
];
